---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  vars_files:
    - ../../configs/disk-virt-sysprep.yaml
    - ../../scripts/ansible/enums.yaml
    - ../../scripts/ansible/common.yaml
  tasks:
    - name: Init
      include_tasks: "{{ repo_dir }}/scripts/ansible/init-task-generation.yaml"
    - name: "Generate {{ task_name }} task"
      template:
        src: "{{ manifest_templates_dir }}/{{ task_name }}.yaml"
        dest: "{{ manifests_output_dir }}/{{ task_name }}.yaml"
        mode: "{{ default_file_mode }}"
    - name: Prepare examples dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ examples_output_dir }}"
        - "{{ examples_taskruns_output_dir }}"
    - name: Generate example task runs
      template:
        src: "{{ examples_templates_dir }}/{{ item }}.yaml"
        dest: "{{ examples_taskruns_output_dir }}/{{ item }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - "{{ task_name }}-taskrun"
        - "{{ task_name }}-taskrun-workspace"
    - name: Prepare readme dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ readme_output_dir_tmp }}"
    - name: Generate README
      template:
        src: "{{ readmes_templates_dir }}/README.md"
        dest: "{{ readme_output_dir }}/README.md"
        mode: "{{ default_file_mode }}"
      vars:
        task_path: "{{ manifests_output_dir }}/{{ task_name }}.yaml"
        task_yaml: "{{ lookup('file', task_path) | from_yaml }}"
    - name: "Delete readme tmp directory"
      file:
        path: "{{ readme_output_dir_tmp }}"
        state: absent
