---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
    - name: baseDvNamespace
      value: <result-disk-namespace>
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-bios-installer
      - name: version
        value: v0.19.0
