apiVersion: v1
kind: Secret
metadata:
  name: {{ item }}
type: Opaque
stringData:
  password: mysecretpassword
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ item }}
spec:
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
    - name: pvc
      value: example-pvc
    - name: customizeCommands
      value: |
        update
        install make,ansible
        delete /var/cache/dnf
        root-password file:/data/password
  workspaces:
    - name: data
      secret:
        name: {{ item }}
