---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    artifacthub.io/maintainers: |
      - name: Karel Simon
        email: ksimon@redhat.com
    tekton.dev/deprecated: "true"
  labels:
    app.kubernetes.io/version: {{ version }}
    artifacthub.io/category: {{ task_category }}
  name: {{ task_name }}
spec:
  params:
    - name: sourceTemplateName
      description: Name of an OpenShift template to copy template from.
      type: string
    - name: sourceTemplateNamespace
      description: Namespace of an source OpenShift template to copy template from. (defaults to active namespace)
      type: string
      default: ""
    - name: targetTemplateName
      description: Name of an target OpenShift template.
      type: string
      default: ""
    - name: targetTemplateNamespace
      description: Namespace of an target OpenShift template to create in. (defaults to active namespace)
      type: string
      default: ""
    - name: allowReplace
      description: Allow replacing already existing template (same combination name/namespace). Allowed values true/false
      type: string
      default: "false"
  results:
    - name: name
      description: The name of a template that was created.
    - name: namespace
      description: The namespace of a template that was created.
  steps:
    - name: copytemplate
      image: "{{ main_image }}:{{ version }}"
      command:
        - copy-template
      args:
        - "--output=yaml"
      env:
        - name: SOURCE_TEMPLATE_NAME
          value: $(params.sourceTemplateName)
        - name: SOURCE_TEMPLATE_NAMESPACE
          value: $(params.sourceTemplateNamespace)
        - name: TARGET_TEMPLATE_NAME
          value: $(params.targetTemplateName)
        - name: TARGET_TEMPLATE_NAMESPACE
          value: $(params.targetTemplateNamespace)
        - name: ALLOW_REPLACE
          value: $(params.allowReplace)
