---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    task.kubevirt.io/associatedServiceAccount: create-datavolume-from-manifest-task
    manifest.params.task.kubevirt.io/type: resource-yaml
    manifest.params.task.kubevirt.io/kind: DataVolume
    manifest.params.task.kubevirt.io/apiVersion: cdi.kubevirt.io/v1beta1
    waitForSuccess.params.task.kubevirt.io/type: boolean
  labels:
    task.kubevirt.io/type: create-datavolume-from-manifest
    task.kubevirt.io/category: create-datavolume
  name: create-datavolume-from-manifest
spec:
  description: >-
    This task creates a DataVolume with oc client. It can optionally wait until
    CDI imports finishes.
  params:
    - name: manifest
      description: YAML manifest of a DataVolume resource to be created.
      type: string
    - name: waitForSuccess
      description: Set to "true" or "false" if container should wait for Ready condition of a DataVolume.
      default: 'false'
      type: string
  results:
    - name: name
      description: The name of DataVolume that was created.
    - name: namespace
      description: The namespace of DataVolume that was created.
  steps:
    - name: create
      image: quay.io/openshift/origin-cli:4.11
      script: |
        #!/usr/bin/env bash

        set -e

        TMP_OBJ_YAML_FILENAME="/tmp/datavolume.yaml"
        TMP_OBJ_RESULTS_FILENAME="/tmp/dv_results"

        echo "$(inputs.params.manifest)" > "$TMP_OBJ_YAML_FILENAME"

        if [[ ! "$(cat $TMP_OBJ_YAML_FILENAME)" == *"kind: DataVolume"* ]] && [[ ! "$(cat $TMP_OBJ_YAML_FILENAME)" == *"kind: DataSource"* ]]; then
            1>&2 echo "manifest does not contain DataVolume or DataSource kind!"
            exit 1
        fi

        oc create -f "$TMP_OBJ_YAML_FILENAME" -o  jsonpath='{.metadata.name} {.metadata.namespace}' > "$TMP_OBJ_RESULTS_FILENAME"

        sed -i 's/ /\n/g' "$TMP_OBJ_RESULTS_FILENAME"
        readarray -t OBJ_OUTPUT_ARRAY < "$TMP_OBJ_RESULTS_FILENAME"

        OBJ_NAME="${OBJ_OUTPUT_ARRAY[0]}"
        OBJ_NAMESPACE="${OBJ_OUTPUT_ARRAY[1]}"

        echo -n "$OBJ_NAME" > /tekton/results/name
        echo -n "$OBJ_NAMESPACE" > /tekton/results/namespace

        echo "Created $OBJ_NAME Datavolume in $OBJ_NAMESPACE namespace."

        if [[ "$(inputs.params.waitForSuccess)" == true ]] && [[ "$TMP_OBJ_YAML_FILENAME" == *"kind: DataVolume"* ]]; then
            echo "Waiting for Ready condition."
            # TODO: detect failed imports and don't wait until wait timeouts
            oc wait "datavolumes.cdi.kubevirt.io/$OBJ_NAME" --namespace="$OBJ_NAMESPACE" --for="condition=Ready" --timeout=720h
        fi

        if [[ "$(inputs.params.waitForSuccess)" == true ]] && [[ "$TMP_OBJ_YAML_FILENAME" == *"kind: DataSource"* ]]; then
            echo "Waiting for Ready condition."
            # TODO: detect failed imports and don't wait until wait timeouts
            oc wait "datasources.cdi.kubevirt.io/$OBJ_NAME" --namespace="$OBJ_NAMESPACE" --for="condition=Ready" --timeout=720h
        fi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-datavolume-from-manifest-task
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - cdi.kubevirt.io
    resources:
      - datasources
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - pods

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-datavolume-from-manifest-task

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-datavolume-from-manifest-task
roleRef:
  kind: ClusterRole
  name: create-datavolume-from-manifest-task
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: create-datavolume-from-manifest-task
