on:
  release:
    types: [published]

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Publish tekton images and generate release manifests
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | podman login -u="${{ secrets.QUAY_BOT }}" --password-stdin quay.io
          export RELEASE_VERSION="${{ steps.get_release.outputs.tag_name }}"
          make release

      - name: Upload kubernetes manifest
        id: kubernetes-manifest 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
          asset_name: kubevirt-tekton-tasks-kubernetes.yaml
          asset_content_type: text/plain

      - name: Upload okd manifest
        id: okd-manifest  
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: manifests/okd/kubevirt-tekton-tasks-okd.yaml
          asset_name: kubevirt-tekton-tasks-okd.yaml
          asset_content_type: text/plain

      - name: Set output variables
        id: vars
        run: |
          # If GITHUB_FORK_USER is changed, a new access token should be set as a repo secret (ACTIONS_TOKEN)
          echo ::set-output name=GITHUB_FORK_USER::"ksimon1"
          echo ::set-output name=RELEASE_VERSION::"${{ steps.get_release.outputs.tag_name }}"
          echo ::set-output name=GH_USER::"Kubevirt-Tekton-tasks Release Automation"
          echo ::set-output name=GH_EMAIL::"ksimon@redhat.com"

      - name: Upload tekton tasks manifests to tekton tasks operator
        run: |
          make generate-yaml-tasks
          # Set git configs to sign the commit
          git config --global user.email ${{ steps.vars.outputs.GH_EMAIL }}
          git config --global user.name ${{ steps.vars.outputs.GH_USER }}
          # Clone the operator repo with a token to allow pushing before creating a PR
          git clone https://${{ steps.vars.outputs.GITHUB_FORK_USER }}:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ steps.vars.outputs.GITHUB_FORK_USER }}/tekton-tasks-operator
          # Authenticate with gh cli
          echo ${{ secrets.ACTIONS_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          rm token.txt
          cd tekton-tasks-operator
          git remote add upstream https://github.com/ksimon1/tekton-tasks-operator
          git fetch upstream
          git checkout main
          git rebase upstream/main
          git checkout -b update-tekton-tasks-manifests-${{ steps.vars.outputs.RELEASE_VERSION }}
          cp ../manifests/okd/kubevirt-tekton-tasks-okd.yaml data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-${{ steps.vars.outputs.RELEASE_VERSION }}.yaml
          cp ../manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-${{ steps.vars.outputs.RELEASE_VERSION }}.yaml
          sed -i "s/\bTektonTasksVersion\s*=.*/TektonTasksVersion = \"${VERSION}\"/g" pkg/operands/version.go
        
          git add .
          git commit -sm "Update tekton tasks manifests to version ${{ steps.vars.outputs.RELEASE_VERSION }}"
          git push --set-upstream origin update-tekton-tasks-manifests-${{ steps.vars.outputs.RELEASE_VERSION }}
          # Create a new PR in the tekton-tasks-operator repo
          gh pr create --repo ksimon1/tekton-tasks-operator \
            --base main \
            --head ${{ steps.vars.outputs.GITHUB_FORK_USER }}:update-tekton-tasks-manifests-${{ steps.vars.outputs.RELEASE_VERSION }} \
            --title "Update tekton tasks manifests to version ${{ steps.vars.outputs.RELEASE_VERSION }}" \
            --body "$(cat << EOF
          Update tekton tasks manifests to version ${{ steps.vars.outputs.RELEASE_VERSION }} 
          **Release note**:
          \`\`\`release-note
          NONE
          \`\`\`
          EOF
          )
          "

      - name: Update tekton tasks manifests
        run: |
          # Set git configs to sign the commit
          git config --global user.email ${{ steps.vars.outputs.GH_EMAIL }}
          git config --global user.name ${{ steps.vars.outputs.GH_USER }}
          # Clone the operator repo with a token to allow pushing before creating a PR
          git clone https://${{ steps.vars.outputs.GITHUB_FORK_USER }}:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ steps.vars.outputs.GITHUB_FORK_USER }}/kubevirt-tekton-tasks
          # Authenticate with gh cli
          echo ${{ secrets.ACTIONS_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          rm token.txt
          cd kubevirt-tekton-tasks
          git remote add upstream https://github.com/ksimon1/kubevirt-tekton-tasks
          git fetch upstream
          git checkout main
          git rebase upstream/main
          git checkout -b update-tekton-tasks-manifests-${{ steps.vars.outputs.RELEASE_VERSION }}
          sed -i "s/export RELEASE_VERSION.*=.*/export RELEASE_VERSION ?=${{ steps.vars.outputs.RELEASE_VERSION }}/g" scripts/makefile-snippets/makefile-release.mk
          make generate-yaml-tasks
          git add .
          git commit -sm "Update tekton tasks manifests to version ${{ steps.vars.outputs.RELEASE_VERSION }}"
          git push --set-upstream origin update-tekton-tasks-manifests-${{ steps.vars.outputs.RELEASE_VERSION }}
          # Create a new PR in the kubevirt-tekton-tasks repo
          gh pr create --repo ksimon1/kubevirt-tekton-tasks \
            --base main \
            --head ${{ steps.vars.outputs.GITHUB_FORK_USER }}:update-tekton-tasks-manifests-${{ steps.vars.outputs.RELEASE_VERSION }} \
            --title "Update tekton tasks manifests to version ${{ steps.vars.outputs.RELEASE_VERSION }}" \
            --body "$(cat << EOF
          Update tekton tasks manifests to version ${{ steps.vars.outputs.RELEASE_VERSION }} 
          **Release note**:
          \`\`\`release-note
          NONE
          \`\`\`
          EOF
          )
          "
